# Generated by Django 5.0.6 on 2025-11-29 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('min_temp', models.FloatField(help_text='Minimum optimal temperature')),
                ('max_temp', models.FloatField(help_text='Maximum optimal temperature')),
                ('min_rainfall', models.FloatField(help_text='Minimum rainfall required (mm)')),
                ('max_rainfall', models.FloatField(help_text='Maximum rainfall required (mm)')),
            ],
        ),
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('estimated_yield', models.FloatField(blank=True, help_text='Estimated yield in quintals', null=True)),
                ('actual_yield', models.FloatField(blank=True, help_text='Actual yield in quintals', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
            ],
        ),
    ]
