# Generated by Django 5.0.6 on 2025-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_diseaselog_recommendationlog_yieldlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaselog',
            name='crop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
